# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          path: master
      
      - name: Create library branch if not existing
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: library

      - name: Checkout library branch
        uses: actions/checkout@v3
        with:
          ref: library
          path: library

      - name: Clear library directory
        run: |
            cd $GITHUB_WORKSPACE/library
            echo "Removed library files:"
            shopt -s extglob
            shopt -s dotglob
            rm -rfv !(".git"|"."|"..")
            shopt -u dotglob
            shopt -u extglob
            echo "Library file list:"
            ls -la
            cd $GITHUB_WORKSPACE

      - name: Move LabVIEW project files to library folder
        run: |
          LVPROJ=$(find $GITHUB_WORKSPACE/master -name *.lvproj)
          echo "LabVIEW project file: ${LVPROJ}"
          LVDIR=$(dirname ${LVPROJ})
          echo "LabVIEW project directory: ${LVDIR}"
          mv $GITHUB_WORKSPACE/master/${LVDIR}/* $GITHUB_WORKSPACE/library
          echo "Library file list:"
          ls -la $GITHUB_WORKSPACE/library
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: library
          repository: library
