# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out master
      - uses: actions/checkout@v3
        with:
          path: master

      # Checks-out library
      - uses: actions/checkout@v3
        with:
          ref: library
          path: library

      - name: Clear library directory
        run: |
            rm -rfv $GITHUB_WORKSPACE/library/*
            ls -la $GITHUB_WORKSPACE/library

      - name: Move LabVIEW project files from master to library direcotry
        run: |
          LVPROJ=$(find $GITHUB_WORKSPACE/master | grep -oP '(?<=\/)[^\/]+(?=\.lvproj)')
          echo ${LVPROJ}
          mv $GITHUB_WORKSPACE/master/${LVPROJ}/* $GITHUB_WORKSPACE/library
          ls -la $GITHUB_WORKSPACE/library
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: library
          repository: $GITHUB_WORKSPACE/library
